### ISSUE TITLE
can't install at mac version 10.8.2

### ISSUE THREAD

**Issue by yuany** [danchoi/vmail#122]
I install vmail using gem, but have some errors, as follow:

ligang.yao@localhost Downloads$sudo gem install vmail-2.7.5.gem
Password:
Building native extensions.  This could take a while...
ERROR:  Error installing vmail-2.7.5.gem:
    ERROR: Failed to build gem native extension.

```
    /Users/ligang.yao/.rvm/rubies/ruby-1.9.3-p327/bin/ruby extconf.rb
```

checking for sqlite3.h... **\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/ligang.yao/.rvm/rubies/ruby-1.9.3-p327/bin/ruby
    --with-sqlite3-dir
    --without-sqlite3-dir
    --with-sqlite3-include
    --without-sqlite3-include=${sqlite3-dir}/include
    --with-sqlite3-lib
    --without-sqlite3-lib=${sqlite3-dir}/lib
    --enable-local
    --disable-local
/Users/ligang.yao/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:369:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /Users/ligang.yao/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:494:in`try_cpp'
    from /Users/ligang.yao/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:958:in `block in find_header'
    from /Users/ligang.yao/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:778:in`block in checking_for'
    from /Users/ligang.yao/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:272:in `block (2 levels) in postpone'
    from /Users/ligang.yao/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:242:in`open'
    from /Users/ligang.yao/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:272:in `block in postpone'
    from /Users/ligang.yao/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:242:in`open'
    from /Users/ligang.yao/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:268:in `postpone'
    from /Users/ligang.yao/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:777:in`checking_for'
    from /Users/ligang.yao/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:957:in `find_header'
    from extconf.rb:34:in`<main>'

Gem files will remain installed in /Users/ligang.yao/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/gems/1.9.1/gems/sqlite3-1.3.6 for inspection.
Results logged to /Users/ligang.yao/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/gems/1.9.1/gems/sqlite3-1.3.6/ext/sqlite3/gem_make.out

**Comment by shulunpro** [comment]
> I installed Xcode, I'm not sure I need install raisinstaller ?

After I install ruby with brew and change the PATH, I run into the same problems.
` echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.zshrc`

So, I delete the export line in .zshrc. Just use built-in ruby and its lib. 

it works.
