### ISSUE TITLE
Problem with parse

### ISSUE THREAD

**Issue by Enrico68** [danchoi/vmail#184]
Whenever I run vmail  I get this error message:

System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse': (<unknown>): could not find expected ':' while scanning a simple key at line 5 column 1 (Psych::SyntaxError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in`parse_stream'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:153:in `parse'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:129:in`load'
    from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.2/lib/vmail/options.rb:65:in `block in parse'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:885:in`initialize'
    from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.2/lib/vmail/options.rb:22:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.2/lib/vmail/options.rb:22:in`parse'
    from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.2/lib/vmail/options.rb:18:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.2/lib/vmail.rb:41:in`new'
    from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.2/lib/vmail.rb:41:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.2/bin/vmail:14:in`<top (required)>'
    from /usr/bin/vmail:23:in `load'
    from /usr/bin/vmail:23:in`<main>'

Mac OS 10.9

**Comment by clemaitre58** [comment]
I have the same problem, what do you mean by : Your .vmailrc may be incorrectly formatted

**Comment by notalex** [comment]
`.vmailrc` is parsed as a YAML file. This error occurs when `.vmailrc` contents do not adhere to the YAML syntax. Please attach your `.vmailrc`, it will help us figure out the syntax error.

**Comment by notalex** [comment]
`.vmailrc` is parsed as a YAML file. This error occurs when `.vmailrc` contents do not adhere to the YAML syntax. Please attach your `.vmailrc`, it will help us figure out the syntax error.

**Comment by clemaitre58** [comment]
username: c.lemaitre58@gmail.com 
password: xxxxxx
password name: Cedric Lemaitre
https://fr.linkedin.com/in/cedric-lemaitre-00342611
NB: I changed the PW by XXXXX

**Comment by notalex** [comment]
Only the first 2 lines are correct. You only need those to get Vmail
working.
