### ISSUE TITLE
VMAIL_ERROR:  Please log in via your web browser

### ISSUE THREAD

**Issue by TheGrandmother** [danchoi/vmail#202]
I keep getting this error when i try to use Vmail.

```
Starting vmail 2.9.6
Setting VMAIL_BROWSER to 'gnome-open'
Setting VMAIL_HTML_PART_READER to 'w3m -dump -T text/html -I utf-8 -O utf-8'
Changing working directory to /home/grandmother/.vmail/default
Using config file: .vmailrc
No contacts file found for auto-completion. See help for how to generate it.
Enter gmail password (won't be visible & won't be persisted):

Starting vmail imap client for henrik.sommerland@gmail.com
INBOX polling disabled.
Working directory: /home/grandmother/.vmail/default
Checking vmail.db version... OK
Connecting to database
Starting Vmail::ImapClient in dir /home/grandmother/.vmail/default
VMAIL_ERROR:  Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)
/usr/lib/ruby/1.9.1/net/imap.rb:1141:in `get_tagged_response'
/usr/lib/ruby/1.9.1/net/imap.rb:1195:in `block in send_command'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/1.9.1/net/imap.rb:1177:in `send_command'
/usr/lib/ruby/1.9.1/net/imap.rb:419:in `login'
/var/lib/gems/1.9.1/gems/vmail-2.9.6/lib/vmail/imap_client.rb:68:in `open'
/var/lib/gems/1.9.1/gems/vmail-2.9.6/lib/vmail/imap_client.rb:526:in `start'
/var/lib/gems/1.9.1/gems/vmail-2.9.6/lib/vmail/imap_client.rb:532:in `daemon'
/var/lib/gems/1.9.1/gems/vmail-2.9.6/lib/vmail.rb:136:in `start_imap_daemon'
/var/lib/gems/1.9.1/gems/vmail-2.9.6/lib/vmail.rb:29:in `start'
/var/lib/gems/1.9.1/gems/vmail-2.9.6/bin/vmail:14:in `<top (required)>'
/usr/local/bin/vmail:23:in `load'
/usr/local/bin/vmail:23:in `<main>'
Starting gmail service at druby://grandmother-lap:40193
/usr/lib/ruby/1.9.1/net/imap.rb:1143:in `get_tagged_response': Unknown command i133mb29434682lfd (Net::IMAP::BadResponseError)
        from /usr/lib/ruby/1.9.1/net/imap.rb:1195:in `block in send_command'
        from /usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
        from /usr/lib/ruby/1.9.1/net/imap.rb:1177:in `send_command'
        from /usr/lib/ruby/1.9.1/net/imap.rb:526:in `block in list'
        from /usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
        from /usr/lib/ruby/1.9.1/net/imap.rb:525:in `list'
        from /var/lib/gems/1.9.1/gems/vmail-2.9.6/lib/vmail/imap_client.rb:166:in `list_mailboxes'
        from /var/lib/gems/1.9.1/gems/vmail-2.9.6/lib/vmail/imap_client.rb:198:in `mailboxes'
        from /var/lib/gems/1.9.1/gems/vmail-2.9.6/lib/vmail/imap_client.rb:185:in `block (3 levels) in mailbox_aliases'
        from /var/lib/gems/1.9.1/gems/vmail-2.9.6/lib/vmail/imap_client.rb:184:in `each'
        from /var/lib/gems/1.9.1/gems/vmail-2.9.6/lib/vmail/imap_client.rb:184:in `block (2 levels) in mailbox_aliases'
        from /var/lib/gems/1.9.1/gems/vmail-2.9.6/lib/vmail/imap_client.rb:183:in `each'
        from /var/lib/gems/1.9.1/gems/vmail-2.9.6/lib/vmail/imap_client.rb:183:in `block in mailbox_aliases'
        from /var/lib/gems/1.9.1/gems/vmail-2.9.6/lib/vmail/imap_client.rb:182:in `each'
        from /var/lib/gems/1.9.1/gems/vmail-2.9.6/lib/vmail/imap_client.rb:182:in `mailbox_aliases'
        from /var/lib/gems/1.9.1/gems/vmail-2.9.6/lib/vmail/imap_client.rb:92:in `select_mailbox'
        from /usr/lib/ruby/1.9.1/drb/drb.rb:1083:in `method_missing'
        from /var/lib/gems/1.9.1/gems/vmail-2.9.6/lib/vmail.rb:82:in `select_mailbox'
        from /var/lib/gems/1.9.1/gems/vmail-2.9.6/lib/vmail.rb:30:in `start'
        from /var/lib/gems/1.9.1/gems/vmail-2.9.6/bin/vmail:14:in `<top (required)>'
        from /usr/local/bin/vmail:23:in `load'
        from /usr/local/bin/vmail:23:in `<main>'
``` 

I have my gmail setup to allow IMAP.

**Comment by tdroxler** [comment]
Same here

**Comment by SiliconKite** [comment]
Same story here. What are the dangers associated with doing this ?

**Comment by alazyworkaholic** [comment]
i'm also having the same problem starting vmail. I enabled both IMAP & less secure access but still get the `VMAIL_ERROR` line, and the `'get_tagged_response': Unknown command j25mb188613092ivg (Net::IMAP::BadResponseError)`

What to do?

**Comment by notalex** [comment]
@alazyworkaholic, please  capture the log from `~/.vmail/<folder_name>/vmail.log` while you run vmail. This wil help us debug this issue further.

**Comment by notalex** [comment]
The following post might be helpful to answer concerns about less secure apps:
https://security.stackexchange.com/questions/66025/what-are-the-dangers-of-allowing-less-secure-apps-to-access-my-google-account

**Comment by notalex** [comment]
If you generate an App password on Google as per the [wiki](https://github.com/danchoi/vmail/wiki/How-to-use-vmail-with-2-step-protected-gmail-account) documentation, then vmail can be used alongwith 2-step-verification.
