### ISSUE TITLE
Error in encoding UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by MauricioAlgalan** [danchoi/vmail#217]
My vmail don't open some e-mails because have a error in encoding: "Error in encoding UTF-8 and ASCII-8BIT".

I tray some older solutions but do not work. I have gems 2.5.0 and vmail 2.9.11.

**Comment by notalex** [comment]
I work with emails encoded in foreign languages and I do not see this issue at my end. It seems like you have ruby 2.5.0 installed and it should be able to handle any encoding.

It would help if I could have access to one of the affected emails. If possible please forward one of the affected emails to *notalexjohnson at gmail*.

**Comment by nbossard** [comment]
Same issue here for all french emails : 

Here is what is displayed instead of email
```
  1 Error.encountered.in.fetch_and_cache(),.message_id.<e_qCcvVCQSGUb8K5KqtRNQ@ismtpd0023p1iad2.sendgrid.net>.[INBOX]:
  2 incompatible.character.encodings:.UTF-8.and.ASCII-8BIT
  3 /Library/Ruby/Gems/2.3.0/gems/vmail-2.9.11/lib/vmail/showing_message.rb:80:in.`fetch_and_cache'
  4 /Library/Ruby/Gems/2.3.0/gems/vmail-2.9.11/lib/vmail/showing_message.rb:30:in.`block.in.show_message'
  5 /Library/Ruby/Gems/2.3.0/gems/vmail-2.9.11/lib/vmail/helpers.rb:10:in.`block.in.retry_if_needed'
  6 /Library/Ruby/Gems/2.3.0/gems/vmail-2.9.11/lib/vmail/helpers.rb:9:in.`times'
  7 /Library/Ruby/Gems/2.3.0/gems/vmail-2.9.11/lib/vmail/helpers.rb:9:in.`retry_if_needed'
  8 /Library/Ruby/Gems/2.3.0/gems/vmail-2.9.11/lib/vmail/showing_message.rb:30:in.`show_message'
  9 /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/drb/drb.rb:1624:in.`perform_without_block'
 10 /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/drb/drb.rb:1584:in.`perform'
 11 /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/drb/drb.rb:1657:in.`block.(2.levels).in.main_loop'
 12 /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/drb/drb.rb:1653:in.`loop'
 13 /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/drb/drb.rb:1653:in.`block.in.main_loop'
```
-------- 

And here is part of vmail.log

```
D, [2019-08-22T22:46:55.206582 #27038] DEBUG -- : Done
D, [2019-08-22T22:46:55.207347 #27038] DEBUG -- : Getting mailbox status
D, [2019-08-22T22:46:55.207408 #27038] DEBUG -- : Getting highest message id
D, [2019-08-22T22:46:55.505289 #27038] DEBUG -- : Highest seqno: 16083
D, [2019-08-22T22:46:55.663267 #27038] DEBUG -- : #search: "\"all\""
D, [2019-08-22T22:46:55.663393 #27038] DEBUG -- : Query: "15984:16083 all"
D, [2019-08-22T22:46:55.806280 #27038] DEBUG -- : - Query got 100 results; max seqno: 16083
D, [2019-08-22T22:46:55.806388 #27038] DEBUG -- : Clearing cached message
D, [2019-08-22T22:46:55.806435 #27038] DEBUG -- : Fetching headers for 100 messages
D, [2019-08-22T22:47:17.785489 #27038] DEBUG -- : Show message: "<T34VEtty6JMfPehg_DFwhA.0@notifications.google.com>"
D, [2019-08-22T22:47:17.785776 #27038] DEBUG -- : - found message <T34VEtty6JMfPehg_DFwhA.0@notifications.google.com>
D, [2019-08-22T22:47:17.785811 #27038] DEBUG -- : - message has plaintext? false
D, [2019-08-22T22:47:17.785831 #27038] DEBUG -- : - full message cache miss
D, [2019-08-22T22:47:17.786059 #27038] DEBUG -- : - fetching message uid 45911
D, [2019-08-22T22:47:18.331975 #27038] DEBUG -- : Error encountered in fetch_and_cache(), message_id <T34VEtty6JMfPehg_DFwhA.0@notifications.google.com> [INBOX]:
incompatible character encodings: UTF-8 and ASCII-8BIT
/Library/Ruby/Gems/2.3.0/gems/vmail-2.9.11/lib/vmail/showing_message.rb:80:in `fetch_and_cache'
/Library/Ruby/Gems/2.3.0/gems/vmail-2.9.11/lib/vmail/showing_message.rb:30:in `block in show_message'
/Library/Ruby/Gems/2.3.0/gems/vmail-2.9.11/lib/vmail/helpers.rb:10:in `block in retry_if_needed'
/Library/Ruby/Gems/2.3.0/gems/vmail-2.9.11/lib/vmail/helpers.rb:9:in `times'
/Library/Ruby/Gems/2.3.0/gems/vmail-2.9.11/lib/vmail/helpers.rb:9:in `retry_if_needed'
/Library/Ruby/Gems/2.3.0/gems/vmail-2.9.11/lib/vmail/showing_message.rb:30:in `show_message'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/drb/drb.rb:1624:in `perform_without_block'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/drb/drb.rb:1584:in `perform'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/drb/drb.rb:1657:in `block (2 levels) in main_loop'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/drb/drb.rb:1653:in `loop'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/drb/drb.rb:1653:in `block in main_loop'
D, [2019-08-22T22:47:18.332050 #27038] DEBUG -- : Showing message message_id: <T34VEtty6JMfPehg_DFwhA.0@notifications.google.com>
```

Thanks for any suggestion on how to solve it.
Nicolas.

**Comment by nbossard** [comment]
Reverted to version 2.9.10 issue is no more present... something failed in 2.9.11 :-)
