### ISSUE TITLE
Charset in mail display should switch to mail encoding

### ISSUE THREAD

**Issue by ghost** [danchoi/vmail#60]
My vim has as default encoding "utf-8". Many emails I get are encoded with iso-8859-1. So every of these emails display special characters (umlauts) wrong.
It would be a nice feature to fetch the charset from the mail-header, switch the vim buffer to this encoding and then display the mail.

Best regards
Florian

**Comment by mturquette** [comment]
I'm still getting this. My google apps account is in french and vmail chokes when I enter my mailbox_aliases in .vmailrc:

```
mailbox_aliases:
  trash: Corbeille
  sent: Messages envoyés
```

Full dump here:

```
~  $ vmail -g
Starting vmail 2.9.4
Setting VMAIL_BROWSER to 'open'
Setting VMAIL_HTML_PART_READER to 'w3m -dump -T text/html -I utf-8 -O utf-8'
Changing working directory to /Users/mturquette/.vmail/default
Using config file: /Users/mturquette/.vmailrc
Using contacts file: vmail-contacts.txt
Logging as mturquette@baylibre.com
#<struct Net::IMAP::TaggedResponse tag="RUBY0001", name="OK", data=#<struct Net::IMAP::ResponseText code=nil, text="mturquette@baylibre.com authenticated (Success)">, raw_data="RUBY0001 OK mturquette@baylibre.com authenticated (Success)\r\n">
Selecting [Gmail]/Messages envoyés
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/imap.rb:1281:in `===': incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string) (Encoding::CompatibilityError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/imap.rb:1281:in `send_string_data'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/imap.rb:1263:in `send_data'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/imap.rb:1200:in `block (2 levels) in send_command'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/imap.rb:1198:in `each'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/imap.rb:1198:in `block in send_command'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/imap.rb:1192:in `send_command'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/imap.rb:453:in `block in select'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/imap.rb:451:in `select'
        from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.4/lib/vmail/contacts_extractor.rb:27:in `block in extract'
        from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.4/lib/vmail/contacts_extractor.rb:17:in `open'
        from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.4/lib/vmail/contacts_extractor.rb:23:in `extract'
        from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.4/lib/vmail/options.rb:79:in `block (2 levels) in parse'
        from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.4/lib/vmail/options.rb:78:in `open'
        from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.4/lib/vmail/options.rb:78:in `block in parse'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:885:in `initialize'
        from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.4/lib/vmail/options.rb:22:in `new'
        from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.4/lib/vmail/options.rb:22:in `parse'
        from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.4/lib/vmail/options.rb:18:in `initialize'
        from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.4/lib/vmail.rb:41:in `new'
        from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.4/lib/vmail.rb:41:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/vmail-2.9.4/bin/vmail:14:in `<top (required)>'
        from /usr/bin/vmail:23:in `load'
        from /usr/bin/vmail:23:in `<main>'
```
